oracle-terraform-modules/terraform-oci-vcn

terraform.tfvars.example
variables.tf

Signed-off-by: Karthic Ravindran <karthic.ravindran@oracle.com>
OCI Provider Variables were removed .Region and compartment id has been kept for resource manager.

Issue #2 Remove provider variables

---

schema.yaml

Signed-off-by: Karthic Ravindran <karthic.ravindran@oracle.com>
Schema yaml file added for Resource manager.

schema for resource manager

---

outputs.tf

Signed-off-by: Dirk Fuchs <difu@mac.com>

PR for Issue #8: Added output for internet gateway

---

CHANGELOG.adoc
docs/terraformoptions.adoc
nat.tf
outputs.tf
servicegateway.tf
variables.tf
vcn.tf

fix input var.region. It is now optional

---

CHANGELOG.adoc
CONTRIBUTING.adoc
CONTRIBUTORS.adoc
docs/codingconventions.adoc
vcn_gateways.tf

- add a codingconvention document
- add new sections on CONTRIBUTING.adoc with focus on documentation update
- fix some headers on CONTRIBUTORS.adoc
- fix typos in vcn_gateways.tf

Update contributing guide

---

CHANGELOG.adoc
CONTRIBUTING.adoc
README.adoc
README.md
docs/codingconventions.adoc
docs/prerequisites.adoc
docs/quickstart.adoc
docs/terraformoptions.adoc
examples/README.md
examples/main.tf
examples/terraform.tfvars.example
examples/variables.tf
outputs.tf
variables.tf
vcn_gateways.tf
versions.tf

Fix Issue #16 (Add a DRG and associate it with the VCN)
Fix Issue #19 (CHANGELOG.md is missing v2.0.0 information)
Fix Issue #15 (would be possible to avoid => REMOVE , ALL default values in any of the modules ?)
Add Deprecation notice for variable names (Issue #24)
Example gets the values from variables
suggested tag for release: v2.2.0

Add feature Create DRG and attach to VCN

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

Adapted from OKE module and OCI Provider repositories
Contains headers to automatically add label to issues.

add GitHub issue templates

---

.gitignore
CHANGELOG.adoc
CONTRIBUTORS.adoc
README.adoc
README.md
docs/prerequisites.adoc
docs/quickstart.adoc
docs/routing_rules.adoc
docs/terraformoptions.adoc
examples/README.md
examples/custom_route_rules/README.md
examples/custom_route_rules/main.tf
examples/main.tf
outputs.tf

- rename default branch from master to main
- update documentation links

release v2.2.0

---

docs/terraformoptions.adoc
terraform.tfvars.example
variables.tf
vcn_gateways.tf

- [x ] My code follows [the style guidelines of this project](../tree/main/docs/codingconventions.adoc)
- [ x] these changes adds any new variables:
- [x ] I have updated [docs/terraformoptions.adoc](../tree/main/docs/terraformoptions.adoc) to include each variable

feat: added support for reserved public IP address for NAT gateway

---

CHANGELOG.adoc
examples/hub-spoke/README.md

feat: release v3.0.0

---

CHANGELOG.adoc
docs/terraformoptions.adoc
examples/custom_route_rules/main.tf
examples/custom_route_rules/terraform.tfvars.example
examples/custom_route_rules/variables.tf
examples/hub-spoke/README.md
examples/hub-spoke/main.tf
examples/hub-spoke/terraform.tfvars.example
examples/hub-spoke/variables.tf
examples/module_composition/main.tf
examples/module_composition/terraform.tfvars.example
examples/module_composition/variables.tf
terraform.tfvars.example
variables.tf
vcn.tf

feat: add ipv6 support for VCN

---

CHANGELOG.adoc
docs/terraformoptions.adoc
examples/custom_route_rules/main.tf
examples/custom_route_rules/terraform.tfvars.example
examples/custom_route_rules/variables.tf
examples/hub-spoke/main.tf
examples/hub-spoke/terraform.tfvars.example
examples/hub-spoke/variables.tf
examples/module_composition/main.tf
examples/module_composition/terraform.tfvars.example
examples/module_composition/variables.tf
examples/rpc/rpc_from_drg_module/main.tf
examples/rpc/rpc_from_drg_module/terraform.tfvars.example
examples/rpc/rpc_from_drg_module/variables.tf
examples/rpc/rpc_from_vcn_module/main.tf
examples/rpc/rpc_from_vcn_module/terraform.tfvars.example
examples/rpc/rpc_from_vcn_module/variables.tf
terraform.tfvars.example
variables.tf
vcn.tf
vcn_gateways.tf

Add defined tags in variables.tf

---

README.adoc
README.md
examples/drg/main.tf
examples/rpc/rpc_from_drg_module/main.tf
outputs.tf
terraform.tfvars.example
variables.tf
vcn_gateways.tf

Close #80 
the module now accepts the attached DRG ID in input.
- [ X] I have updated the README introduction section (README.md)

fix route tables with drg destination

---

examples/custom_route_rules/.terraform.lock.hcl
examples/custom_route_rules/main.tf
examples/drg/main.tf
examples/hub-spoke/.terraform.lock.hcl
examples/hub-spoke/main.tf
examples/module_composition/main.tf
examples/rpc/rpc_from_drg_module/main.tf
examples/rpc/rpc_from_vcn_module/main.tf

close #83  
Examples are now using relative path to submodules instead of Terraform registry path. 
A comment shows how to use the Terraform registry

fixed examples to use local path for submodules

---

docs/terraformoptions.adoc
modules/subnet/outputs.tf
modules/subnet/subnet.tf
modules/subnet/variables.tf
modules/subnet/versions.tf
outputs.tf
terraform.tfvars.example
variables.tf
vcn.tf

Provided options to create subnet in the VCN module

Subnet Module

---

vcn_defaultresources.tf

Signed-off-by: Ali Mukadam <ali.mukadam@oracle.com>
Terraform apply
- [] Running `terraform apply` on each example provided with this module provisions the intended resource(s) without any errors.
- [] Modifying module's *Input Variables* after initial provisioning behaves as intended, i.e: any updatable properties are amended without recreation of the resource(s).
Note: *If you are not an Oracle employee, to contribute to an Oracle-sponsored open-source project, you need to sign the [Oracle Contributor Agreement …

fix: Handle out-of-band changes to default sec list. closes #98

---

README.adoc
README.md

docs: removed broken link

---

docs/src/chapter_9.md
docs/src/css/general.css

docs: styling

---

docs/src/chapter_9.md
docs/src/css/general.css

docs: changed code style in terraformoptions and increased padding

---

docs/book.toml
docs/mdbook-admonish.css
docs/src/chapter_1.md
docs/src/chapter_2.md
docs/src/chapter_4.md
docs/src/chapter_5.md
docs/src/chapter_6.md
docs/src/chapter_7.md
docs/src/chapter_8.md
docs/src/chapter_9.md
docs/src/css/mdbook-admonish.css

docs: added admonitions, error in terraform options

---

examples/custom_route_rules/README.md
examples/custom_route_rules/terraform.tfvars.example
vcn_gateways.tf

This PR resolve issue reported in the following tickets:
- #89 
- https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/514

feat: lpg introspection route rules - close #89

---

outputs.tf

Fix for Issue #116

---

modules/subnet/subnet.tf
modules/subnet/variables.tf
terraform.tfvars.example
variables.tf
vcn.tf

Issue #115 - Allow availability domain configurable per subnet

---

terraform.tfvars.example
variables.tf
vcn.tf

fix: for Issue -63 add VCN (subnets) Logging

---

locals.tf
terraform.tfvars.example
variables.tf
vcn_gateways.tf

The change added the ability for full naming support for route tables rather than just the prefix #103. The existing functionality to specify just prefix is maintained.
Using terraform init, plan and apply

feat: Full naming support for route tables rather than just the prefix
